apiVersion: v1
kind: Pod
metadata:
  name: nginx-cp
  labels:
    app: nginx
spec:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  nodeName: controlplane
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: host
      mountPath: /host
    securityContext:
      privileged: true
  volumes:
  - name: host
    hostPath: 
      path: "/"
